### ISSUE TITLE
旧版vs环境能不能发一下

### ISSUE THREAD

**Issue by H1W0XXX** [lihaochen910/DBDHunter#3]
装了半天XNA发现vs2022装不上，还得卸载vs2022，安装旧版vs，能不能发一下xna的环境文件

**Comment by H1W0XXX** [comment]
能不能发一下这个文件夹的压缩打包 
C:\Program Files\dotnet\sdk\8.0.300\Microsoft\XNA Game Studio

**Comment by lihaochen910** [comment]
不需要安装XNA就能跑，你可以发下错误信息看一下

**Comment by H1W0XXX** [comment]
PS D:\dbd2\DBDHunter\src\DBDHunter> dotnet build
  Determining projects to restore...
  所有项目均是最新的，无法还原。
D:\dbd2\DigitalRune\Source\DigitalRune.Geometry\DigitalRune.Geometry(XNA,Win).csproj(74,3): error MSB4019: 找不到导入的项目“C:\Program Files\dotnet\sdk\8.0.300\Microsoft\XNA Game S
tudio\Microsoft.Xna.GameStudio.targets”。请确认 Import 声明“C:\Program Files\dotnet\sdk\8.0.300\\Microsoft\XNA Game Studio\Microsoft.Xna.GameStudio.targets”中的表达式正确， 且文件位于磁盘上。
D:\dbd2\DigitalRune\Source\DigitalRune.Mathematics\DigitalRune.Mathematics(XNA,Win).csproj(74,3): error MSB4019: 找不到导入的项目“C:\Program Files\dotnet\sdk\8.0.300\Microsoft\XNA
Game Studio\Microsoft.Xna.GameStudio.targets”。请确认 Import 声明“C:\Program Files\dotnet\sdk\8.0.300\\Microsoft\XNA Game Studio\Microsoft.Xna.GameStudio.targets”中的表达式 正确，且文件位于磁盘上
。

生成失败。

D:\dbd2\DigitalRune\Source\DigitalRune.Geometry\DigitalRune.Geometry(XNA,Win).csproj(74,3): error MSB4019: 找不到导入的项目“C:\Program Files\dotnet\sdk\8.0.300\Microsoft\XNA Game S
tudio\Microsoft.Xna.GameStudio.targets”。请确认 Import 声明“C:\Program Files\dotnet\sdk\8.0.300\\Microsoft\XNA Game Studio\Microsoft.Xna.GameStudio.targets”中的表达式正确， 且文件位于磁盘上。
D:\dbd2\DigitalRune\Source\DigitalRune.Mathematics\DigitalRune.Mathematics(XNA,Win).csproj(74,3): error MSB4019: 找不到导入的项目“C:\Program Files\dotnet\sdk\8.0.300\Microsoft\XNA
Game Studio\Microsoft.Xna.GameStudio.targets”。请确认 Import 声明“C:\Program Files\dotnet\sdk\8.0.300\\Microsoft\XNA Game Studio\Microsoft.Xna.GameStudio.targets”中的表达式 正确，且文件位于磁盘上
。
    0 个警告
    2 个错误

已用时间 00:00:00.86

**Comment by H1W0XXX** [comment]
DigitalRune是直接从git clone下来的

**Comment by lihaochen910** [comment]
仓库中libs目录里有编译好的DigitalRune库文件，直接添加引用上去就好。不用手动编译DigitalRune

**Comment by H1W0XXX** [comment]
dotnet add package Microsoft.Extensions.Logging
<ItemGroup>
  <Reference Include="DigitalRune">
    <HintPath>..\libs\DigitalRune.dll</HintPath>
  </Reference>
  <Reference Include="DigitalRune.Geometry">
    <HintPath>..\libs\DigitalRune.Geometry.dll</HintPath>
  </Reference>
  <Reference Include="DigitalRune.Logging">
    <HintPath>..\libs\DigitalRune.Logging.dll</HintPath>
  </Reference>
  <Reference Include="DigitalRune.Mathematics">
    <HintPath>..\libs\DigitalRune.Mathematics.dll</HintPath>
  </Reference>
  <Reference Include="DigitalRune.Persistence">
    <HintPath>..\libs\DigitalRune.Persistence.dll</HintPath>
  </Reference>
</ItemGroup>
