### ISSUE TITLE
报错找不到 Murder

### ISSUE THREAD

**Issue by H1W0XXX** [lihaochen910/DBDHunter#4]
PS D:\dbd2\DBDHunter\src\DBDHunter.Editor\bin\Release\net8.0> ls

    目录: D:\dbd2\DBDHunter\src\DBDHunter.Editor\bin\Release\net8.0

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2024/7/19     17:55                cs
d-----         2024/7/19     17:55                de
d-----         2024/7/19     17:55                es
d-----         2024/7/19     17:55                fr
d-----         2024/7/19     17:55                it
d-----         2024/7/19     17:55                ja
d-----         2024/7/19     17:55                ko
d-----         2024/7/19     17:55                pl
d-----         2024/7/19     17:55                pt-BR
d-----         2024/7/19     17:55                resources
d-----         2024/7/19     17:55                ru
d-----         2024/7/19     17:55                runtimes
d-----         2024/7/19     17:55                tr
d-----         2024/7/19     17:55                zh-Hans
d-----         2024/7/19     17:55                zh-Hant
-a----         2024/7/19     17:53          58880 Bang.Analyzers.dll
-a----         2024/7/19     17:53          40736 Bang.Analyzers.pdb
-a----         2024/7/19     17:53          75264 Bang.dll
-a----         2024/7/19     17:53          80384 Bang.Generator.dll
-a----         2024/7/19     17:53          40360 Bang.Generator.pdb
-a----         2024/7/19     17:53          37232 Bang.pdb
-a----         2024/7/19     17:54          54658 DBDHunter.deps.json
-a----         2024/7/19     17:54        1111552 DBDHunter.dll
-a----         2024/7/19     17:55          54158 DBDHunter.Editor.deps.json
-a----         2024/7/19     17:55          23552 DBDHunter.Editor.dll
-a----         2024/7/19     17:55         148992 DBDHunter.Editor.exe
-a----         2024/7/19     17:55          13812 DBDHunter.Editor.pdb
-a----         2024/7/19     17:55            390 DBDHunter.Editor.runtimeconfig.json
-a----         2024/7/19     17:54         142848 DBDHunter.exe
-a----         2024/7/19     17:54         636772 DBDHunter.pdb
-a----         2024/7/19     17:54           1511 DBDHunter.runtimeconfig.json
-a----          2024/7/2     11:39         238080 DigitalRune.dll
-a----          2024/7/2     11:39         520192 DigitalRune.Geometry.dll
-a----          2024/7/2     11:39         311440 DigitalRune.Geometry.pdb
-a----          2024/7/2     11:39           9728 DigitalRune.Logging.dll
-a----          2024/7/2     11:39          10528 DigitalRune.Logging.pdb
-a----          2024/7/2     11:39         504832 DigitalRune.Mathematics.dll
-a----          2024/7/2     11:39         320360 DigitalRune.Mathematics.pdb
-a----          2024/7/2     11:39         137252 DigitalRune.pdb
-a----          2024/7/2     11:39          78848 DigitalRune.Persistence.dll
-a----          2024/7/2     11:39          45896 DigitalRune.Persistence.pdb
-a----          2024/6/2      3:41         800256 FNA.dll
-a----         2024/7/19     16:51           1809 Gum.deps.json
-a----         2024/7/19     16:51          95744 Gum.dll
-a----         2024/7/19     16:51         142848 Gum.exe
-a----         2024/7/19     16:51          76104 Gum.pdb
-a----         2024/7/19     16:51            268 Gum.runtimeconfig.json
-a----          2017/5/5      7:33         212008 Humanizer.dll
-a----         2024/7/19     18:07            386 imgui.ini
-a----        2023/11/20      7:14         306688 ImGui.NET.dll
-a----        2020/10/20      2:47          14720 Microsoft.Bcl.AsyncInterfaces.dll
-a----         2021/11/9     11:25        5824128 Microsoft.CodeAnalysis.CSharp.dll
-a----         2021/11/9     11:28         811136 Microsoft.CodeAnalysis.CSharp.Workspaces.dll
-a----         2021/11/9     11:10        2643072 Microsoft.CodeAnalysis.dll
-a----         2021/11/9     11:20        3226216 Microsoft.CodeAnalysis.Workspaces.dll
-a----        2023/10/31     22:58          64288 Microsoft.Extensions.DependencyInjection.Abstractions.dll
-a----        2023/10/31     22:59          92320 Microsoft.Extensions.DependencyInjection.dll
-a----        2023/10/31     22:59          65184 Microsoft.Extensions.Logging.Abstractions.dll
-a----        2023/10/31     22:59          50848 Microsoft.Extensions.Logging.dll
-a----        2023/10/31     22:59          64672 Microsoft.Extensions.Options.dll
-a----        2023/10/31     22:58          43680 Microsoft.Extensions.Primitives.dll
-a----         2024/7/19     17:48        2151424 Murder.dll
-a----         2024/7/19     17:53          13014 Murder.Editor.deps.json
-a----         2024/7/19     17:53         697344 Murder.Editor.dll
-a----         2024/7/19     17:53         154112 Murder.Editor.exe
-a----         2024/7/19     17:53         225508 Murder.Editor.pdb
-a----         2024/7/19     16:51            390 Murder.Editor.runtimeconfig.json
-a----         2024/7/19     17:53         154112 Murder.exe
-a----         2024/7/19     17:48        1349688 Murder.pdb
-a----         2024/7/19     17:53          52224 Murder.Serializer.dll
-a----         2024/7/19     17:53          40540 Murder.Serializer.pdb
-a----         2024/7/19     17:48         937239 Murder.xml
-a----         2024/4/10      1:24         437288 SkiaSharp.dll
-a----         2016/11/5     12:55          24840 System.Composition.AttributedModel.dll
-a----         2016/11/5     12:55          59128 System.Composition.Convention.dll
-a----         2016/11/5     12:55          62184 System.Composition.Hosting.dll
-a----         2016/11/5     12:55          29928 System.Composition.Runtime.dll
-a----         2016/11/5     12:55          64760 System.Composition.TypedParts.dll
-a----        2020/11/26     10:01          67464 System.IO.Pipelines.dll

PS D:\dbd2\DBDHunter\src\DBDHunter.Editor\bin\Release\net8.0> .\DBDHunter.Editor.exe
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Murder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。
File name: 'Murder, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at DBDHunter.Editor.Program.Main()

**Comment by lihaochen910** [comment]
murder仓库需要clone下来，然后添加项目引用

**Comment by H1W0XXX** [comment]
这是编译好以后报的错

**Comment by lihaochen910** [comment]
最后都在一个目录中，还有别的编译和找不到文件的问题就自己折腾一下吧
