### ISSUE TITLE
如何把Generator从AActor数组中区分开

### ISSUE THREAD

**Issue by YokiZheng** [lihaochen910/DBDHunter#5]
![629afb07ae69643f11e8e6a255101cc6](https://github.com/user-attachments/assets/6cf894e5-6511-4303-9ffd-432ec279388e)

大佬您好，如您所见，我通过遍历全AActor的形式把游戏内所有的entity都绘制出来了，但是遇到个棘手的问题，我无法分辨哪些entity是Generator。我有办法可以区分人类和屠夫，因为这两个对象都有个叫EPlayerRole的枚举，通过判断是1还是2即可确定是人类或者杀手，同样的方法也适用于板子，但不适用于电机，因为我没在sdk中找到发电机相关的enum。请问您是如何解决的呢？

**Comment by lihaochen910** [comment]
发电机这种你需要拿到AActor的Class(UObject::Class)的Name字段(UObject::Name)，需要用到GNames偏移来解析FName类型，然后就是字符串对比了。
<img width="451" alt="image" src="https://github.com/user-attachments/assets/31e6b3e2-1f54-41ce-a4ea-ed7b7fc7b991">

**Comment by YokiZheng** [comment]
谢谢！我去试一下

**Comment by shuaige1112** [comment]
ok

**Comment by YokiZheng** [comment]
大佬您好，请问人物的上钩次数是保存在人物的entity对象里的嘛？还是说需要自己计算？另外，还有个小问题，人物的骨骼有在entity里保存嘛?

(我说的entity皆是GWorld->Level->OwnAct->ActPoint)

**Comment by lihaochen910** [comment]
上钩次数没弄过不清楚，自己dump一下sdk去看。人物骨骼看SDK里的ACharacter::Mesh

**Comment by lihaochen910** [comment]
骨骼绘制的话可以去UC上找UE4 Bone ESP能找到相关的，详细也可以看我这个里面也有

**Comment by YokiZheng** [comment]
好的！thanks

**Comment by YokiZheng** [comment]
![e69804fdfeb94f1a3684562df636ee0](https://github.com/user-attachments/assets/f9285d3e-5a16-4153-8f63-7d1e7daa3eec)
最后个小问题，我发现图腾entity的FName是固定的，附不附加技能都是这个值（0x18），请问有什么办法可以获取图腾上附加的技能嘛？

**Comment by lihaochen910** [comment]
ATotem::_boundPerks, 拜托看一下SDK，都在SDK里
