### ISSUE TITLE
Need help: bang, gum not found 

### ISSUE THREAD

**Issue by asdat3** [lihaochen910/DBDHunter#6]
gum.csproj
bang.csproj

not found and the matching .analysers when trying to open DBDHunter
rest looks good, but no idea, I am unsure how to use the murder engine

my directory is currently:
```
>dir
 Datenträger in Laufwerk C: ist OS
 Volumeseriennummer: BCD3-B3B6

 Verzeichnis von C:\Users\qschilling\Downloads\subdbd

08.08.2024  15:45    <DIR>          .
08.08.2024  15:27    <DIR>          ..
08.08.2024  16:02    <DIR>          DBDHunter
08.08.2024  15:45    <DIR>          DigitalRune
08.08.2024  15:45    <DIR>          murder
```

I played arround with moving src files but it didnt work.

Also is a DMA Card needed for the project to work?

**Comment by asdat3** [comment]
nvm found it out what was wrong there, now the issue is:

```
 Determining projects to restore...
  Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Geometry\DigitalRune.Geometry.csproj" wird übersprungen
  , da es nicht gefunden wurde.
  Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Logging\DigitalRune.Logging.csproj" wird übersprungen,
  da es nicht gefunden wurde.
  Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Mathematics\DigitalRune.Mathematics.csproj" wird übersp
  rungen, da es nicht gefunden wurde.
  Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Geometry\DigitalRune.Geometry.csproj" wird übersprungen
  , da es nicht gefunden wurde.
  Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Logging\DigitalRune.Logging.csproj" wird übersprungen,
  da es nicht gefunden wurde.
  Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Mathematics\DigitalRune.Mathematics.csproj" wird übersp
  rungen, da es nicht gefunden wurde.
```

**Comment by lihaochen910** [comment]
> nvm found it out what was wrong there, now the issue is:
> 
> ```
>  Determining projects to restore...
>   Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Geometry\DigitalRune.Geometry.csproj" wird übersprungen
>   , da es nicht gefunden wurde.
>   Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Logging\DigitalRune.Logging.csproj" wird übersprungen,
>   da es nicht gefunden wurde.
>   Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Mathematics\DigitalRune.Mathematics.csproj" wird übersp
>   rungen, da es nicht gefunden wurde.
>   Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Geometry\DigitalRune.Geometry.csproj" wird übersprungen
>   , da es nicht gefunden wurde.
>   Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Logging\DigitalRune.Logging.csproj" wird übersprungen,
>   da es nicht gefunden wurde.
>   Das Projekt "C:\Users\qschilling\Downloads\subdbd\DigitalRune.Mathematics\DigitalRune.Mathematics.csproj" wird übersp
>   rungen, da es nicht gefunden wurde.
> ```

I put the compiled library in the libs folder. You can modify the csproj file to change the actual project reference to the dll reference in the lib folder.

**Comment by asdat3** [comment]
Any recommendations for DMA Hardware? preferably with firmware for an affordable price.
Thank you for the informations I will try to link the projects

**Comment by lihaochen910** [comment]
> Any recommendations for DMA Hardware? preferably with firmware for an affordable price. Thank you for the informations I will try to link the projects

CaptainDMA or Immortal DMA or Lurker, I use Immortal DMA myself
For DBD, you don't need to use expensive custom firmware, the normal firmware will do.

**Comment by asdat3** [comment]
most cant even be shipped to germany 😞 
not sure if its worth since DMA software is often not even much cheaper than non-DMA especially since the fuser is needed I guess, I am unsure if we should continue this discussion here if you are interested in helping me out with that decision tho, its kyudev on discord :)

**Comment by asdat3** [comment]
bought some, I still cant build the Hunter tho, some DigitalRune stuff is missing even tho I added all ur .dll files from the libs folder.

I am rather new to CPP and only really understand the module concepts JS and Python so this is very confusing for me sorry. Do you have any kind of instructions to show how to import the projects like it is needed in this case?

**Comment by asdat3** [comment]
I manually added all the csproj from DigitalRune, some like the DigitalRune.logging do not exist, which version are you using????

There are also errors when trying to build that some D: Gitworkspace,... stuff doesnt exist, I do not even have a D drive on this device, can you please adjust the code to not use full paths? or at least tell me where these paths are set?
