### ISSUE TITLE
请原谅我的无知,编译报错无法独自解决

### ISSUE THREAD

**Issue by Ben-John933** [lihaochen910/DBDHunter#7]
编译全部成功,但是murder在依赖里有个感叹号(但是正确识别到了文件路径也能跳转到项目),解决方案文件夹也有digtalrune的dll,但是打开dbdhunter.editor会报错unhandled exception. system.invalidoperationexception nullable object must have a value,一闪而过窗口

**Comment by Ben-John933** [comment]
我试着用五月份版本murder编译,运行editor报错又不一样,找不到文件public key一大串,如果有成功编译的人士希望能够将成功步骤告诉我.

**Comment by lihaochen910** [comment]
贴上你的报错信息，以便大家能帮到你

**Comment by Ben-John933** [comment]
![Uploading 屏幕截图 2024-08-13 203857.png…]()

**Comment by Ben-John933** [comment]
![屏幕截图 2024-08-13 203857](https://github.com/user-attachments/assets/671761d5-d4c5-44d0-b9f2-71770a763b8d)

**Comment by Ben-John933** [comment]
![屏幕截图 2024-08-13 204315](https://github.com/user-attachments/assets/0d1f45bb-506c-4725-82fc-39b3a72136d8)
![屏幕截图 2024-08-13 204148](https://github.com/user-attachments/assets/1850ce47-90f5-4c46-9674-55b105bbaa78)

**Comment by Ben-John933** [comment]
![Uploading 屏幕截图 2024-08-13 204615.png…]()

**Comment by Ben-John933** [comment]
![屏幕截图 2024-08-13 204615](https://github.com/user-attachments/assets/78961649-8baf-4431-911a-04fcdf04ff7c)
